#ifndef CONSTANTS_IS_DEF
#define CONSTANTS_IS_DEF

#define WIN_WIDTH 1280
#define WIN_HEIGHT 754

#define MAP_WIDTH 50
#define MAP_HEIGHT 20

#define MARIO_INITIAL_POSX 320
#define MARIO_INITIAL_POSY 0

#define SECURITY_TOP 192
#define SECURITY_BOTTOM 448
#define SECURITY_LEFT 256
#define SECURITY_RIGHT 512

#define DELTA_CHAIN_REACTION 25
#define TANK_HZ 2000

#define TILE 64

#define MAP_OBJECTS_NB 14

#endif